# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to=b'partners', verbose_name='\u041b\u043e\u0433\u043e\u0442\u0438\u043f')),
                ('url', models.URLField(verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u044c')),
                ('label_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u044c')),
                ('label_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u044c')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('is_active', models.BooleanField(verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u044b\u0439')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
