# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_ru', models.CharField(max_length=25, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_en', models.CharField(max_length=25, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('position', models.PositiveSmallIntegerField(verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f')),
                ('show_on_main', models.BooleanField(default=False, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439')),
            ],
            options={
                'ordering': ('position',),
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0430',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='CategorySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('max_competitors_count', models.PositiveIntegerField(default=32, help_text='\u041c\u0430\u043a\u0441\u0438\u043c\u0430\u043b\u044c\u043d\u043e\u0435 \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432 \u0432 \u0442\u0443\u0440\u043d\u0438\u0440\u0435', verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432')),
                ('last_tournaments_count', models.PositiveIntegerField(default=8, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0442\u0443\u0440\u043d\u0438\u0440\u043e\u0432 \u0434\u043e \u043e\u0431\u043d\u0443\u043b\u0435\u043d\u0438\u044f \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u043e\u0432')),
                ('result_tournaments_count', models.PositiveIntegerField(default=4, help_text='\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u044b \u0441\u043a\u043e\u043b\u044c\u043a\u0438\u0445 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0445 \u0442\u0443\u0440\u043d\u0438\u0440\u043e\u0432 \u0443\u0447\u0438\u0442\u044b\u0432\u0430\u044e\u0442\u0441\u044f \u043f\u0440\u0438 \u0440\u0430\u0441\u0447\u0435\u0442\u0435 \u0440\u0435\u0439\u0442\u0438\u043d\u0433\u0430 \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0430', verbose_name='\u0423\u0447\u0438\u0442\u044b\u0432\u0430\u0435\u043c\u043e\u0435 \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0442\u0443\u0440\u043d\u0438\u0440\u043e\u0432')),
            ],
            options={
                'verbose_name': '\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b \u0440\u0430\u0441\u0447\u0435\u0442\u0430 \u0440\u0435\u0439\u0442\u0438\u043d\u0433\u0430 \u0434\u043b\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
                'verbose_name_plural': '\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b \u0440\u0430\u0441\u0447\u0435\u0442\u0430 \u0440\u0435\u0439\u0442\u0438\u043d\u0433\u0430 \u0434\u043b\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=250, verbose_name='\u0418\u043c\u044f')),
                ('firstName_ru', models.CharField(max_length=250, null=True, verbose_name='\u0418\u043c\u044f')),
                ('firstName_en', models.CharField(max_length=250, null=True, verbose_name='\u0418\u043c\u044f')),
                ('lastName', models.CharField(max_length=250, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('lastName_ru', models.CharField(max_length=250, null=True, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('lastName_en', models.CharField(max_length=250, null=True, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a',
                'verbose_name_plural': '\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('address', models.CharField(max_length=250, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('address_ru', models.CharField(max_length=250, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('address_en', models.CharField(max_length=250, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='\u0428\u0438\u0440\u043e\u0442\u0430')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='\u0414\u043e\u043b\u0433\u043e\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u041c\u0435\u0441\u0442\u043e \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f',
                'verbose_name_plural': '\u041c\u0435\u0441\u0442\u0430 \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=10, verbose_name='\u041c\u0435\u0441\u0442\u043e')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Competitor', verbose_name='\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a')),
            ],
            options={
                'verbose_name': '\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442',
                'verbose_name_plural': '\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='ResultSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
                ('competitors', models.ManyToManyField(related_name='resultsets', through='rating.Results', to='rating.Competitor')),
                ('locations', models.ManyToManyField(related_name='resultsets', to='rating.Location', verbose_name='\u041c\u0435\u0441\u0442\u0430 \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0421\u0435\u0442\u043a\u0430 \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u043e\u0432',
                'verbose_name_plural': '\u0421\u0435\u0442\u043a\u0438 \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=b'', verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0440\u0430\u0432\u0438\u043b\u0430')),
                ('text_ru', models.TextField(default=b'', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0440\u0430\u0432\u0438\u043b\u0430')),
                ('text_en', models.TextField(default=b'', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0440\u0430\u0432\u0438\u043b\u0430')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0430\u0432\u0438\u043b\u043e',
                'verbose_name_plural': '\u041f\u0440\u0430\u0432\u0438\u043b\u0430',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('start_date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f')),
                ('squashclub_url', models.CharField(blank=True, max_length=200, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0442\u0443\u0440\u043d\u0438\u0440 \u043d\u0430 squashclub.ru')),
                ('is_past', models.BooleanField(default=False, verbose_name='\u0422\u0443\u0440\u043d\u0438\u0440 \u043f\u0440\u043e\u0448\u0435\u043b (\u0443\u0447\u0438\u0442\u044b\u0432\u0430\u0442\u044c \u043f\u0440\u0438 \u043f\u043e\u0434\u0441\u0447\u0435\u0442\u0435 \u0440\u0435\u0439\u0442\u0438\u043d\u0433\u0430)')),
            ],
            options={
                'verbose_name': '\u0422\u0443\u0440\u043d\u0438\u0440',
                'verbose_name_plural': '\u0422\u0443\u0440\u043d\u0438\u0440\u044b',
            },
        ),
        migrations.AddField(
            model_name='resultset',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Tournament', verbose_name='\u0422\u0443\u0440\u043d\u0438\u0440'),
        ),
        migrations.AddField(
            model_name='results',
            name='resultset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.ResultSet', verbose_name='\u0421\u0435\u0442\u043a\u0430 \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u043e\u0432'),
        ),
        migrations.AddField(
            model_name='category',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.CategorySettings'),
        ),
    ]
