# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 06:32
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone


def update_datetime_fields(apps, schema_editor):

    def _update(objects, fields):
        for obj in objects:
            for field in fields:
                value = getattr(obj, field)
                if value is not None:
                    value = timezone.make_naive(value, timezone=timezone.utc)
                    value = timezone.make_aware(value)
                    setattr(obj, field, value)
            obj.save()


    _update(
        apps.get_model("league.League").objects.all(),
        ('tournament_a_datetime', 'tournament_b_datetime')
    )
    _update(
        apps.get_model("league.Game").objects.all(),
        ('start_datetime', 'end_datetime')
    )
    _update(
        apps.get_model("league.Rating").objects.all(),
        ('datetime', )
    )


class Migration(migrations.Migration):
    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_datetime_fields),
    ]


