# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='added_via_api',
            field=models.BooleanField(default=False, verbose_name='\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0430 \u0447\u0435\u0440\u0435\u0437 API'),
        ),
    ]
