# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 21:01
from __future__ import unicode_literals

from django.db import migrations


def copy_data(apps, schema_editor):
    for league in apps.get_model("league.League").objects.all():
        lts_a = league.leaguetournamentset_set.create(
            name_ru=u'Категория A',
            name_en=u'Category A',
            number=16,
            datetime=league.tournament_a_datetime,
            is_filled=league.is_tournament_data_filled,
        )
        lts_b = league.leaguetournamentset_set.create(
            name_ru=u'Категория B',
            name_en=u'Category B',
            datetime=league.tournament_b_datetime,
            is_filled=league.is_tournament_data_filled,
        )
        for lc in league.leaguecompetitor_set.all():
            lts = None
            if lc.tournament_category == 'A':
                lts = lts_a
            elif lc.tournament_category == 'B':
                lts = lts_b
            lc.tournament_set = lts
            lc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_add_league_tournament_set'),
    ]

    operations = [
        migrations.RunPython(copy_data),
    ]
