# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_fill_league_tournament_sets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeagueAlterTournament',
        ),
        migrations.CreateModel(
            name='LeagueTournamentWithSets',
            fields=[
            ],
            options={
                'verbose_name': '\u0418\u0442\u043e\u0433\u043e\u0432\u044b\u0439 \u0442\u0443\u0440\u043d\u0438\u0440 \u041b\u0438\u0433\u0438 (\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438)',
                'proxy': True,
                'verbose_name_plural': '\u0418\u0442\u043e\u0433\u043e\u0432\u044b\u0435 \u0442\u0443\u0440\u043d\u0438\u0440\u044b \u041b\u0438\u0433\u0438 (\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438)',
            },
            bases=('league.league',),
        ),
        migrations.RemoveField(
            model_name='league',
            name='is_tournament_data_filled',
        ),
        migrations.RemoveField(
            model_name='league',
            name='location',
        ),
        migrations.RemoveField(
            model_name='league',
            name='tournament_a_datetime',
        ),
        migrations.RemoveField(
            model_name='league',
            name='tournament_b_datetime',
        ),
        migrations.RemoveField(
            model_name='leaguecompetitor',
            name='tournament_category',
        ),
    ]
