# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_set_league_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruled_leagues', to='flatpages.FlatPage', verbose_name='\u041f\u0440\u0430\u0432\u0438\u043b\u0430 \u0440\u0430\u0441\u0447\u0435\u0442\u0430 \u0440\u0435\u0439\u0442\u0438\u043d\u0433\u0430'),
        ),
    ]
