# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 08:47
from __future__ import unicode_literals

from django.db import migrations


def set_rules(apps, schema_editor):
    for league in apps.get_model("league.League").objects.all():
        fp = apps.get_model("flatpages.Flatpage").objects.filter(url='/leagues/rules/').first()
        if fp:
            league.rules = fp
            league.save()


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_league_rules'),
    ]

    operations = [
        migrations.RunPython(set_rules),
    ]
