# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
        ('league', '0010_set_league_rules'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaguecompetitor',
            unique_together=set([('competitor', 'league')]),
        ),
    ]
