# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-26 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_add_unique_together_league_competitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguesettings',
            name='rating_off_last_days',
            field=models.PositiveIntegerField(default=4, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0445 \u0434\u043d\u0435\u0439 \u043b\u0438\u0433\u0438, \u043a\u043e\u0433\u0434\u0430 \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u044b \u043d\u0430\u043a\u0430\u043f\u043b\u0438\u0432\u0430\u044e\u0442\u0441\u044f, \u043d\u043e \u0440\u0435\u0439\u0442\u0438\u043d\u0433 \u043d\u0435 \u043e\u0431\u043d\u043e\u0432\u043b\u044f\u0435\u0442\u0441\u044f'),
        ),
    ]
