# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-13 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_leaguecompetitor_alter_tournament_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.URLField(verbose_name='\u041a\u043e\u0434')),
            ],
            options={
                'verbose_name': '\u0413\u0440\u0443\u043f\u043f\u0430 \u043b\u0438\u0433',
                'verbose_name_plural': '\u0413\u0440\u0443\u043f\u043f\u044b \u043b\u0438\u0433',
            },
        ),
        migrations.AddField(
            model_name='league',
            name='division',
            field=models.IntegerField(null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0434\u0438\u0432\u0438\u0437\u0438\u043e\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='league',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.LeagueGroup'),
        ),
    ]
