# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-13 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_auto_20190714_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguegroup',
            name='slug',
            field=models.CharField(max_length=25, verbose_name='\u041a\u043e\u0434'),
        ),
    ]
