# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-14 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_auto_20190714_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='leaguegroup',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='\u0422\u0435\u043a\u0443\u0449\u0430\u044f'),
        ),
        migrations.AddField(
            model_name='leaguegroup',
            name='rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruled_league_group', to='flatpages.FlatPage', verbose_name='\u041f\u0440\u0430\u0432\u0438\u043b\u0430 \u0440\u0430\u0441\u0447\u0435\u0442\u0430 \u0440\u0435\u0439\u0442\u0438\u043d\u0433\u0430')
        ),
        migrations.AddField(
            model_name='leaguegroup',
            name='statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stated_league_group', to='flatpages.FlatPage', verbose_name='\u041f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435 \u043b\u0438\u0433\u0438'),
        ),
        migrations.AddField(
            model_name='leaguegroup',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u043d\u0430 \u0441\u0430\u0439\u0442\u0435'),
        ),
    ]
