# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-14 15:20
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_auto_20190714_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguecompetitor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
    ]
