# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-03 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_leaguecompetitor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguecompetitor',
            name='is_moved',
            field=models.BooleanField(default=False, verbose_name='\u041f\u0435\u0440\u0435\u043c\u0435\u0449\u0435\u043d \u0432 \u0434\u0440\u0443\u0433\u0443\u044e \u043b\u0438\u0433\u0443'),
        ),
    ]
