# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-29 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0019_leaguecompetitor_is_moved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguesettings',
            name='delta_formula',
            field=models.CharField(default=b'N + (r2-r1)/(SOFTEN_COEF-TRUST_DELTA)', max_length=255, verbose_name='\u0424\u043e\u0440\u043c\u0443\u043b\u0430 DELTA'),
        ),
    ]
