# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-01 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0021_leaguecompetitorleaguechange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguecompetitorleaguechange',
            options={'verbose_name': '\u041f\u0435\u0440\u0435\u043c\u0435\u0449\u0435\u043d\u0438\u0435 \u043c\u0435\u0436\u0434\u0443 \u0434\u0438\u0432\u0438\u0437\u0438\u043e\u043d\u0430\u043c\u0438', 'verbose_name_plural': '\u041f\u0435\u0440\u0435\u043c\u0435\u0449\u0435\u043d\u0438\u044f \u043c\u0435\u0436\u0434\u0443 \u0434\u0438\u0432\u0438\u0437\u0438\u043e\u043d\u0430\u043c\u0438'},
        ),
        migrations.RemoveField(
            model_name='league',
            name='show_last_days_results',
        ),
    ]
