# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-03 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0022_auto_20191001_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguecompetitorleaguechange',
            name='new_rating',
            field=models.FloatField(blank=True, verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433 \u0432 \u043d\u043e\u0432\u043e\u0439 \u043b\u0438\u0433\u0435'),
        ),
        migrations.AlterField(
            model_name='leaguecompetitorleaguechange',
            name='old_league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_league_changes', to='league.League', verbose_name='\u041b\u0438\u0433\u0430 (\u0441\u0442\u0430\u0440\u0430\u044f)'),
        ),
    ]
